[package]
name = "vecrypto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memmap = "0.7"
unicase = "2.6.0"
case_insensitive_hashmap = "1.0.0"